# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: "MemCheck build and test"

on:
  pull_request:
    branches:
      - master

jobs:
  build-test:
    name: "MemCheck compilation and test"

    runs-on: windows-latest

    env:
      NETCORE_VERSION: "5.0.100"
      COMPIL_CONFIG: "Release"
      PUBLISH_FOLDER: "./Published"
      AZURE_WEBAPP_NAME: "memcheckfr"
      AZURE_FUNCTION_NAME: "memcheck-notifier"

    steps:
    - uses: actions/checkout@v2

    - name: "Set up .NET Core on machine (version ${{env.NETCORE_VERSION}})"
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{env.NETCORE_VERSION}}

    - name: "Clean with dotnet"
      run: dotnet clean --configuration ${{env.COMPIL_CONFIG}}

    - name: "Restore NuGet packages"
      run: dotnet restore

    - name: "Build the root sln with dotnet"
      run: dotnet build --no-restore --configuration ${{env.COMPIL_CONFIG}}

    - name: "Run unit tests"
      run: dotnet test --configuration ${{env.COMPIL_CONFIG}}

    - name: "Publish: prepare the projects for deployment"
      run: dotnet publish --no-build --configuration ${{env.COMPIL_CONFIG}} -o ${{env.PUBLISH_FOLDER}} --no-self-contained MemCheck.WebUI

    - name: "Telling size of publish folder"
      run: du -sh ${{env.PUBLISH_FOLDER}}

    - name: Upload published version as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: MemCheck
        path: ${{env.PUBLISH_FOLDER}}
